namespace RawInput.Win32
{
    internal static class Win32Consts
    {
        internal const int KEYBOARD_OVERRUN_MAKE_CODE = 255;
        internal const int WM_APPCOMMAND = 793;
        internal const int FAPPCOMMANDMASK = 61440;
        internal const int FAPPCOMMANDMOUSE = 32768;
        internal const int FAPPCOMMANDOEM = 4096;
        internal const int WM_INPUT_DEVICE_CHANGE = 254;
        internal const int WM_INPUT = 255;
        internal const int WM_KEYFIRST = 256;
        internal const int WM_KEYDOWN = 256;
        internal const int WM_KEYUP = 257;
        internal const int WM_SYSKEYDOWN = 260;
        internal const int WM_KEYLAST = 264;
        internal const int WM_MOUSEFIRST = 512;
        internal const int WM_MOUSEMOVE = 512;
        internal const int WM_LBUTTONDOWN = 513;
        internal const int WM_LBUTTONUP = 514;
        internal const int WM_LBUTTONDBLCLK = 515;
        internal const int WM_RBUTTONDOWN = 516;
        internal const int WM_RBUTTONUP = 517;
        internal const int WM_RBUTTONDBLCLK = 518;
        internal const int WM_MBUTTONDOWN = 519;
        internal const int WM_MBUTTONUP = 520;
        internal const int WM_MBUTTONDBLCLK = 521;
        internal const int WM_MOUSEWHEEL = 522;
        internal const int WM_MOUSEHWHEEL = 526;
        internal const int WM_MOUSELAST = 526;
        internal const int WM_USB_DEVICECHANGE = 537;
        internal const int PM_NOREMOVE = 0;
        internal const int PM_REMOVE = 1;
        internal const int PM_NOYIELD = 2;
        internal const int RI_KEY_MAKE = 0;
        internal const int RI_KEY_BREAK = 1;
        internal const int RI_KEY_E0 = 2;
        internal const int RI_KEY_E1 = 4;
        internal const int RI_MOUSE_BUTTON_1_DOWN = 1; // Left mouse button
        internal const int RI_MOUSE_BUTTON_1_UP = 2;
        internal const int RI_MOUSE_BUTTON_2_DOWN = 4; // Right mouse button
        internal const int RI_MOUSE_BUTTON_2_UP = 8;
        internal const int RI_MOUSE_BUTTON_3_DOWN = 16; // Middle mouse button
        internal const int RI_MOUSE_BUTTON_3_UP = 32;
        internal const int RI_MOUSE_BUTTON_4_DOWN = 64; // 'Back' mouse button
        internal const int RI_MOUSE_BUTTON_4_UP = 128;
        internal const int RI_MOUSE_BUTTON_5_DOWN = 256; // 'Forward' mouse button
        internal const int RI_MOUSE_BUTTON_5_UP = 512;
        internal const int RI_MOUSE_WHEEL = 1024; // Wheel Delta is stored in usButtonData
        internal const int MK_LBUTTON = 1; // MK refers to Windows message constants
        internal const int MK_RBUTTON = 2;
        internal const int MK_SHIFT = 4;
        internal const int MK_CONTROL = 8;
        internal const int MK_MBUTTON = 16;
        internal const int MK_XBUTTON1 = 32;
        internal const int MK_XBUTTON2 = 64;
        internal const int VK_LBUTTON = 1; // VK refers to Virtual Key code constants
        internal const int VK_RBUTTON = 2;
        internal const int VK_MBUTTON = 4;
        internal const int VK_XBUTTON1 = 5;
        internal const int VK_XBUTTON2 = 6;
        internal const int VK_SHIFT = 16;
        internal const int VK_CONTROL = 17;
        internal const int VK_MENU = 18;
        internal const int VK_ZOOM = 251;
        internal const int VK_LSHIFT = 160;
        internal const int VK_RSHIFT = 161;
        internal const int VK_LCONTROL = 162;
        internal const int VK_RCONTROL = 163;
        internal const int VK_LMENU = 164;
        internal const int VK_RMENU = 165;
        internal const int SC_SHIFT_L = 42;
        internal const int SC_SHIFT_R = 54;
        internal const int RIM_INPUT = 0;
        internal const int RIM_INPUTSINK = 1;
        internal const int MOUSE_MOVE_RELATIVE = 0;
        internal const int MOUSE_MOVE_ABSOLUTE = 1;
        internal const int MOUSE_VIRTUAL_DESKTOP = 2;
        internal const int MOUSE_ATTRIBUTES_CHANGED = 4;
    }
}